name: "Draft release"

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Tag name to use"
        required: true
        type: string

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          name: Version ${{ inputs.tag_name }}
          tag: ${{ inputs.tag_name }}
          version: v${{ inputs.tag_name }}
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
