name: "Push to s3"

on:
  workflow_call:
    inputs:
      s3_bucket_name:
        description: "Name of s3 bucket"
        required: true
        type: string
      source_dir:
        description: "source directory to push to s3"
        required: true
        type: string
      destination_dir:
        description: "Destination folder within s3 - if ommited then files will be pushed into the root of the bucket"
        required: false
        type: string
        default: ""
      aws_role_to_assume:
        description: "AWS role ARN to assume for the push - you can find this in the AWS console called ga-s3-${bucket-name}-role"
        required: true
        type: string
      aws_region:
        description: "AWS region"
        default: "eu-west-1"
        type: string


permissions:
  id-token: write
  contents: read

jobs:
  push-folder:
    name: "Push to s3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS access
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Push contents to s3

        run: aws s3 cp ${{inputs.source_dir}} s3://${{inputs.s3_bucket_name}}/${{inputs.destination_dir}} --recursive
